### ISSUE TITLE
Use custom type errors to catch, e.g. types like "IntegerType' 33"

### ISSUE THREAD

**Issue by mrkgnao** [llvm-hs/llvm-hs-typed#3]

**Comment by cocreature** [comment]
Great suggestion, catching more errors is definitely desirable!

However, your specific example `IntegerType' 33` is actually valid LLVM IR! So that’s definitely not something that we want to prevent.

That example is interesting for another reason: `IntegerType'` is currently just a type constructor and afaik there is no way to prevent it from being applied to certain types. So we would need to introduce a type family for every constructor where we want this kind of validation which seems a bit unwieldily (although one could argue that the improved user experience makes it worth it).

So as a first step, we should collect some examples of what we want to prevent and then try to come up with a consistent API for how we can handle this.

**Comment by sdiehl** [comment]
LLVM does actually support arbitrary sized integers ``i1, i2, i32, i64, i1942652,...``
beyond what the CPU providers. https://llvm.org/docs/LangRef.html#integer-type

**Comment by sdiehl** [comment]
The signature is currently indexed by a type-level Nat.

```haskell 
IntegerType' Nat
```

So I think this should be fine as it's constrained to pure positive numbers up to whatever GHC supports which should be fine unless we put obscenely high values in and the C++ doesn't like it. But enormously sized integers is a pretty odd path anyways.

**Comment by cocreature** [comment]
> So I think this should be fine as it only allows it's constrained to pure positive numbers up to whatever GHC supports which should be fine unless we put obscenely high values in and the C++ doesn't like it.

Yeah I don’t think, integer sizes are something that we need to worry about but there might be other things that we could prevent or if they are already prevented, produce better error messages using custom type errors. (Although I don’t have any examples offhand).

**Comment by sdiehl** [comment]
There doesn't seem to be any continued interest from the OP, so I'm going to close.
